- name: Clone Repo
  git:
    repo: '{{ repository }}'
    dest: '/home/{{ ansible_user }}/{{ directory }}'
    version: '{{branch}}'
    force: yes
    accept_hostkey: yes
    key_file: '/home/{{ ansible_user }}/.ssh/cgus-bot-key'
  tags:
    - setup
    - update
  register: git_clone_result

# It would have been a lot better to inline vault the .env variables here
# but it seems to only work in yaml files
- name: 'Assemble secrets and common .env file'
  assemble:
    src: '{{ env_directory }}'
    dest: '/home/{{ ansible_user }}/{{ directory }}/.env'
    remote_src: False

- name: Print some debug information
  debug:
    msg: '{{ git_clone_result | to_nice_json }}'
  tags: debug_info

- name: Build the image
  become: yes
  community.general.docker_image:
    source: build
    build:
      network: host
      pull: yes
      path: '/home/{{ ansible_user }}/{{ directory }}'
    name: '{{ directory }}:{{ git_clone_result.after[:7] }}'
    force_source: yes

- name: Start the container
  become: yes
  community.general.docker_container:
    name: '{{ directory }}-1'
    image: '{{ directory }}:{{ git_clone_result.after[:7] }}'
    restart: yes
    state: started
    restart_policy: unless-stopped
    etc_hosts:
      'mongo1': '172.17.0.1'
      'mongo2': '172.17.0.1'
      'mongo3': '172.17.0.1'
    env:
      PROCESSOR_ID: '1'
    ports:
      - '{{ port }}:4000'

- name: Start the second container
  become: yes
  when: nb_processors == '2'
  community.general.docker_container:
    name: '{{ directory }}-2'
    image: '{{ directory }}:{{ git_clone_result.after[:7] }}'
    restart: yes
    state: started
    restart_policy: unless-stopped
    etc_hosts:
      'mongo1': '172.17.0.1'
      'mongo2': '172.17.0.1'
      'mongo3': '172.17.0.1'
    env:
      PROCESSOR_ID: '2'
      NB_TWEETS_TO_SCRAPE: '6000'
      MIN_PRIORITY: '2'
      API: 'false'
      USER_BOT_SCORES: 'false'

- name: Start the third container
  become: yes
  when: nb_processors == '3'
  community.general.docker_container:
    name: '{{ directory }}-3'
    image: '{{ directory }}:{{ git_clone_result.after[:7] }}'
    restart: yes
    state: started
    restart_policy: unless-stopped
    etc_hosts:
      'mongo1': '172.17.0.1'
      'mongo2': '172.17.0.1'
      'mongo3': '172.17.0.1'
    env:
      PROCESSOR_ID: '3'
      NB_TWEETS_TO_SCRAPE: '6000'
      MIN_PRIORITY: '2'
      API: 'false'
      USER_BOT_SCORES: 'false'

- name: Prune containers and images
  become: yes
  community.docker.docker_prune:
    containers: yes
    images: yes
    networks: false
    volumes: false
    builder_cache: false
