- name: Clone Repo
  git:
    repo: '{{ repository }}'
    dest: '/home/{{ ansible_user }}/{{ app }}'
    version: '{{branch}}'
    force: yes
    accept_hostkey: yes
    key_file: '/home/{{ ansible_user }}/.ssh/cgus-bot-key'
  tags:
    - setup
    - update

- debug:
    msg: "Deploying '{{repository}}#{{branch}}' in folder '{{app}}' and copying {{ env_file }}"

- name: Build the image
  become: yes
  community.general.docker_image:
    source: build
    build:
      network: host
      pull: yes
      args:
        ENV_FILE: '{{ env_file }}'
      path: '/home/{{ ansible_user }}/{{ app }}'
    name: '{{ app }}'
    force_source: yes

- name: Start the container
  become: yes
  community.general.docker_container:
    name: '{{ app }}-1'
    image: '{{ app }}'
    restart: yes
    env:
      PROCESSOR_ID: '1'
- name: Start the second container
  become: yes
  community.general.docker_container:
    name: '{{ app }}-2'
    image: '{{ app }}'
    restart: yes
    env:
      PROCESSOR_ID: '2'
      NB_TWEETS_TO_SCRAPE: '10000'
      MIN_PRIORITY: '2'
