all:
  vars:
    ansible_user: debian
    repository: 'https://github.com/ambanum/information-manipulation-analyzer-processor.git'
    nb_processors: '1'
    ansible_host: 51.89.231.68
    branch: 'main'
  children:
    preprod:
      hosts:
        preproduction:
          branch: 'develop'
          directory: 'ima-processor-preproduction'
          port: '7822'
          env_directory: '.env.preproduction'
    prod:
      hosts:
        production:
          directory: 'ima-processor-production'
          port: '7022'
          env_directory: '.env.production'
        tflmi-production:
          directory: 'ima-processor-tflmi-production'
          port: '7024'
          env_directory: '.env.tflmi.production'
        ambnum-production:
          directory: 'ima-processor-ambnum-production'
          port: '7026'
          env_directory: '.env.ambnum.production'
        spis-production:
          directory: 'ima-processor-spis-production'
          port: '7028'
          env_directory: '.env.spis.production'
